# Generated by Django 3.1.2 on 2021-01-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
