# Generated by Django 3.1.6 on 2021-02-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0007_pizzamodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzamodel',
            name='category',
        ),
    ]
